name: Run Python Script with API Interaction

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai pyyaml

    - name: Run the script
      env:
        OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}
      run: python src/translate-biographies.py

    # Add new files to the data folder and commit
    - name: Commit and push data folder changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/*
        git commit -m "Update data files" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


