name: Run Python Script with API Interaction

on:
  schedule:
    # This runs the workflow every 8 hours
    - cron: '0 */8 * * *'

jobs:
  run_script:
    name: Process Files from ${{ matrix.start }} to ${{ matrix.end }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        start: [4000, 4500, 5000, 5500, 6000, 6500]
        end: [4499, 4999, 5499, 5999, 6499, 6999]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai pyyaml

    - name: Pull latest changes
      run: |
        git pull origin main

    - name: Run the script
      env:
        OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}
      run: python src/translate-biographies_github_actions.py --start ${{ matrix.start }} --end ${{ matrix.end }}

    - name: commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
